In [1]:
import pandas as pd
df = pd.read_csv("NEW_RF_Predicted.csv")

In [3]:
df.head()

,Average State Income,Contact Method,Age Group,Gender,Scam Category,Scam Type,Amount_lost,State_New South Wales,State_Northern Territory,State_Queensland,State_South Australia,State_Tasmania,State_Victoria,State_Western Australia,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,1776.9,0.203304,5.0,1,0.331957,0.092726,NaN,0,0,0,1,0,0,0,4,5.750536
1,1882.0,0.234301,6.0,0,0.298117,0.065103,NaN,0,0,0,0,0,1,0,6,8.949000
2,1935.7,0.203304,0.0,0,0.298117,0.099654,NaN,1,0,0,0,0,0,0,4,1.241242
3,1935.7,0.203304,4.0,0,0.298117,0.099654,600.0,1,0,0,0,0,0,0,73,79.203119
4,1935.7,0.141753,3.0,0,0.030376,0.028244,13717.0,1,0,0,0,0,0,0,2,2.080000

In [5]:
# First, round the values to 6 decimal places to match the keys in the mapping
df['Contact Method'] = df['Contact Method'].round(6)

# Now apply the mapping
df['Contact Method'] = df['Contact Method'].map({
    0.234301: 'Email',
    0.203304: 'Text message',
    0.196909: 'Phone call',
    0.141753: 'Social media/Online forums',
    0.099609: 'Internet',
    0.062972: 'Mobile apps',
    0.033085: 'Mail',
    0.026024: 'In person',
    0.001066: 'unspecified',
    0.000977: 'Fax'
})

# Preview result
df.head()

,Average State Income,Contact Method,Age Group,Gender,Scam Category,Scam Type,Amount_lost,State_New South Wales,State_Northern Territory,State_Queensland,State_South Australia,State_Tasmania,State_Victoria,State_Western Australia,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,1776.9,Text message,5.0,1,0.331957,0.092726,NaN,0,0,0,1,0,0,0,4,5.750536
1,1882.0,Email,6.0,0,0.298117,0.065103,NaN,0,0,0,0,0,1,0,6,8.949000
2,1935.7,Text message,0.0,0,0.298117,0.099654,NaN,1,0,0,0,0,0,0,4,1.241242
3,1935.7,Text message,4.0,0,0.298117,0.099654,600.0,1,0,0,0,0,0,0,73,79.203119
4,1935.7,Social media/Online forums,3.0,0,0.030376,0.028244,13717.0,1,0,0,0,0,0,0,2,2.080000

In [7]:
# First, round the Scam Type values to 6 decimal places
df['Scam Type'] = df['Scam Type'].round(6)

# Mapping dictionary for Scam Type
scam_type_mapping = {
    0.099654: 'Phishing',
    0.098499: 'Other',
    0.097611: 'Online shopping',
    0.092726: 'False billing',
    0.087752: 'Identity theft',
    0.072875: 'Classified',
    0.065103: 'Hacking',
    0.057332: 'Investment',
    0.045608: 'Remote access',
    0.035438: 'Dating and romance',
    0.033085: 'Threats to life, arrest or other',
    0.032507: 'Rebate',
    0.028244: 'Jobs and employment',
    0.027267: 'Travel, prizes and lottery',
    0.026557: 'Overpayment',
    0.024203: 'inheritance and unexpected money',
    0.023759: 'Health and medical products',
    0.016653: 'Ransomware and malware',
    0.016520: 'Mobile premium services',
    0.008837: 'Fake charity',
    0.005729: 'Betting and sports investment',
    0.002132: 'Pyramid schemes',
    0.001910: 'Psychic and clairvoyant'
}

# Apply the mapping
df['Scam Type'] = df['Scam Type'].map(scam_type_mapping)

# Preview the result
df.head()

,Average State Income,Contact Method,Age Group,Gender,Scam Category,Scam Type,Amount_lost,State_New South Wales,State_Northern Territory,State_Queensland,State_South Australia,State_Tasmania,State_Victoria,State_Western Australia,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,1776.9,Text message,5.0,1,0.331957,False billing,NaN,0,0,0,1,0,0,0,4,5.750536
1,1882.0,Email,6.0,0,0.298117,Hacking,NaN,0,0,0,0,0,1,0,6,8.949000
2,1935.7,Text message,0.0,0,0.298117,Phishing,NaN,1,0,0,0,0,0,0,4,1.241242
3,1935.7,Text message,4.0,0,0.298117,Phishing,600.0,1,0,0,0,0,0,0,73,79.203119
4,1935.7,Social media/Online forums,3.0,0,0.030376,Jobs and employment,13717.0,1,0,0,0,0,0,0,2,2.080000

In [11]:
# Mapping from number (as float) back to age group labels
age_group_reverse_mapping = {
    0.0: "Under 18",
    1.0: "18 - 24",
    2.0: "25 - 34",
    3.0: "35 - 44",
    4.0: "45 - 54",
    5.0: "55 - 64",
    6.0: "65 and over",
}

# Apply the reverse mapping
df["Age Group"] = df["Age Group"].map(age_group_reverse_mapping)

# Preview the result
df.head()

,Average State Income,Contact Method,Age Group,Gender,Scam Category,Scam Type,Amount_lost,State_New South Wales,State_Northern Territory,State_Queensland,State_South Australia,State_Tasmania,State_Victoria,State_Western Australia,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,1776.9,Text message,55 - 64,1,0.331957,False billing,NaN,0,0,0,1,0,0,0,4,5.750536
1,1882.0,Email,65 and over,0,0.298117,Hacking,NaN,0,0,0,0,0,1,0,6,8.949000
2,1935.7,Text message,Under 18,0,0.298117,Phishing,NaN,1,0,0,0,0,0,0,4,1.241242
3,1935.7,Text message,45 - 54,0,0.298117,Phishing,600.0,1,0,0,0,0,0,0,73,79.203119
4,1935.7,Social media/Online forums,35 - 44,0,0.030376,Jobs and employment,13717.0,1,0,0,0,0,0,0,2,2.080000

In [13]:
# List of one-hot encoded state columns
state_columns = [
    'State_New South Wales',
    'State_Northern Territory',
    'State_Queensland',
    'State_South Australia',
    'State_Tasmania',
    'State_Victoria',
    'State_Western Australia'
]

# Recreate 'State' column from one-hot encoding
df['State'] = df[state_columns].idxmax(axis=1)

# Remove the 'State_' prefix to get clean state names
df['State'] = df['State'].str.replace('State_', '', regex=False)

# Drop the one-hot columns
df.drop(columns=state_columns, inplace=True)

# Preview the result
df.head()

,Average State Income,Contact Method,Age Group,Gender,Scam Category,Scam Type,Amount_lost,Actual_Number_of_Reports,Predicted_Number_of_Reports,State
0,1776.9,Text message,55 - 64,1,0.331957,False billing,NaN,4,5.750536,South Australia
1,1882.0,Email,65 and over,0,0.298117,Hacking,NaN,6,8.949000,Victoria
2,1935.7,Text message,Under 18,0,0.298117,Phishing,NaN,4,1.241242,New South Wales
3,1935.7,Text message,45 - 54,0,0.298117,Phishing,600.0,73,79.203119,New South Wales
4,1935.7,Social media/Online forums,35 - 44,0,0.030376,Jobs and employment,13717.0,2,2.080000,New South Wales

In [15]:
new_order = [
    'Age Group', 
    'State', 
    'Average State Income', 
    'Scam Type', 
    'Contact Method', 
    'Amount_lost', 
    'Actual_Number_of_Reports', 
    'Predicted_Number_of_Reports'
]

df = df[new_order]

In [17]:
df.head()

,Age Group,State,Average State Income,Scam Type,Contact Method,Amount_lost,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,55 - 64,South Australia,1776.9,False billing,Text message,NaN,4,5.750536
1,65 and over,Victoria,1882.0,Hacking,Email,NaN,6,8.949000
2,Under 18,New South Wales,1935.7,Phishing,Text message,NaN,4,1.241242
3,45 - 54,New South Wales,1935.7,Phishing,Text message,600.0,73,79.203119
4,35 - 44,New South Wales,1935.7,Jobs and employment,Social media/Online forums,13717.0,2,2.080000

In [19]:
df['Predicted_Number_of_Reports'] = df['Predicted_Number_of_Reports'].round(2)
df.head()

,Age Group,State,Average State Income,Scam Type,Contact Method,Amount_lost,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,55 - 64,South Australia,1776.9,False billing,Text message,NaN,4,5.75
1,65 and over,Victoria,1882.0,Hacking,Email,NaN,6,8.95
2,Under 18,New South Wales,1935.7,Phishing,Text message,NaN,4,1.24
3,45 - 54,New South Wales,1935.7,Phishing,Text message,600.0,73,79.20
4,35 - 44,New South Wales,1935.7,Jobs and employment,Social media/Online forums,13717.0,2,2.08

In [21]:
df['Predicted_Number_of_Reports'] = df['Predicted_Number_of_Reports'].clip(lower=0)
df.head()

,Age Group,State,Average State Income,Scam Type,Contact Method,Amount_lost,Actual_Number_of_Reports,Predicted_Number_of_Reports
0,55 - 64,South Australia,1776.9,False billing,Text message,NaN,4,5.75
1,65 and over,Victoria,1882.0,Hacking,Email,NaN,6,8.95
2,Under 18,New South Wales,1935.7,Phishing,Text message,NaN,4,1.24
3,45 - 54,New South Wales,1935.7,Phishing,Text message,600.0,73,79.20
4,35 - 44,New South Wales,1935.7,Jobs and employment,Social media/Online forums,13717.0,2,2.08

In [23]:
df.to_csv("Updated_RF2.csv", index=False)